language: node_js

node_js:
  - node

git:
  depth: 3

cache:
  yarn: true
  directories:
    - .npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install

script: yarn test
